/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-error": "#ffffff",
                "surface-variant": "#e1e2e4",
                "on-secondary": "#ffffff",
                "on-primary-container": "#90a8ff",
                "tertiary-fixed-dim": "#ffb691",
                "secondary-fixed-dim": "#bdc5eb",
                "on-surface": "#191c1e",
                "on-tertiary-fixed": "#341100",
                "on-tertiary": "#ffffff",
                "tertiary-fixed": "#ffdbcb",
                "on-primary-fixed": "#00164e",
                "surface-container": "#edeef0",
                "secondary": "#555d7e",
                "primary-container": "#1e3a8a",
                "on-secondary-fixed": "#111a37",
                "surface-container-high": "#e7e8ea",
                "surface-container-highest": "#e1e2e4",
                "on-primary-fixed-variant": "#264191",
                "on-primary": "#ffffff",
                "surface-dim": "#d9dadc",
                "on-tertiary-fixed-variant": "#773205",
                "on-error-container": "#93000a",
                "inverse-on-surface": "#f0f1f3",
                "background": "#f8f9fb",
                "on-tertiary-container": "#f39461",
                "outline-variant": "#c5c5d3",
                "surface-container-lowest": "#ffffff",
                "secondary-container": "#d0d8ff",
                "error-container": "#ffdad6",
                "surface-bright": "#f8f9fb",
                "primary-fixed": "#dce1ff",
                "surface-container-low": "#f3f4f6",
                "on-secondary-container": "#555e7f",
                "primary": "#00236f",
                "tertiary-container": "#6e2c00",
                "outline": "#757682",
                "tertiary": "#4b1c00",
                "inverse-surface": "#2e3132",
                "surface-tint": "#4059aa",
                "primary-fixed-dim": "#b6c4ff",
                "success": "#16a34a",
                "error": "#ba1a1a",
                "inverse-primary": "#b6c4ff",
                "secondary-fixed": "#dce1ff",
                "on-secondary-fixed-variant": "#3d4565",
                "on-background": "#191c1e",
                "surface": "#f8f9fb",
                "on-surface-variant": "#444651"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"],
                "manrope": ["Manrope"]
            }
        },
    },
    plugins: [],
}