-- Allow daily repeated notification emails.
-- Previously the UNIQUE(notification_key, recipient_user_id) constraint meant
-- each notification could only be delivered once per recipient *ever*.
-- With daily recurring emails, we need a new row per day so drop the old
-- unique and add a composite index that the Edge Function uses for daily dedup.
--
-- Safe to rerun.

-- 1. Drop the old unique constraint (name generated by Postgres convention).
--    Postgres truncates long auto-generated names, so we try all possible variants.
ALTER TABLE public.notification_email_deliveries
  DROP CONSTRAINT IF EXISTS notification_email_deliveries_notification_key_recipient_u_key;

-- Truncated variant actually used by Postgres:
ALTER TABLE public.notification_email_deliveries
  DROP CONSTRAINT IF EXISTS notification_email_deliveries_notification_key_recipient_us_key;

-- Also try the shorter naming convention in case Postgres used it.
ALTER TABLE public.notification_email_deliveries
  DROP CONSTRAINT IF EXISTS notification_email_deliveries_notification_key_recipient_user_key;

-- 2. Add index for efficient daily dedup lookups:
--    "Has this notification already been sent to this recipient today?"
CREATE INDEX IF NOT EXISTS idx_ned_daily_dedup
  ON public.notification_email_deliveries (notification_key, recipient_user_id, sent_at DESC)
  WHERE status = 'sent';